version: '3'

services:
    game:
      build: ./game
      volumes: 
        - ./game:/game
      ports:
        - "4001:4001"
    game-build:
      build: ./game
      volumes: 
        - ./game:/game
      command: npm run build
    dev:
      build: .
      volumes: 
        - .:/app
      ports:
        - "4000:4000"
      environment:
        - NODE_ENV=development
      depends_on:
        - game
    server: 
      build: .
      volumes: 
        - .:/app
        - ./game/build:/app/game/build
      ports:
        - "80:80"
      environment:
        - NODE_ENV=production
        - PORT=80
      depends_on:
        - game-build